name: Pull Request BCheckChecker

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Validate BChecks
        run: |
          [ $(sha256sum BCheckChecker-1.5.jar | awk '{ print $1 }') = '6fba62e4fe2984ef60668f2d6455738a4d35f2ac1db8c32fdc5c1098034cc436' ]
          java -jar BCheckChecker-1.5.jar

